// Generated by GitHub Actions
name = 'CraftMaven;
filters = ["MCP", "Forge", "Spigot", "APIs"];
const artifacts = [];
artifacts.push({
  name: 'lwjgl',
  groupId: 'org',
  latestVersion: '',
  files: '2',
  description: 'Artifact from org',
  lastUpdated: '2025-03-12',
  versions: 1,
  license: 'MIT',
  category: 'APIs'
});
artifacts.push({
  name: 'lwjgl',
  groupId: 'org',
  latestVersion: '',
  files: '2',
  description: 'Artifact from org',
  lastUpdated: '2025-03-12',
  versions: 1,
  license: 'MIT',
  category: 'APIs'
});
artifacts.push({
  name: 'lwjgl',
  groupId: 'org',
  latestVersion: '',
  files: '2',
  description: 'Artifact from org',
  lastUpdated: '2025-03-12',
  versions: 1,
  license: 'MIT',
  category: 'APIs'
});
