// Generated by GitHub Actions
name = 'CraftMaven';
filters = ["MCP", "Forge", "Spigot", "APIs"];
const artifacts = [];
artifacts.push({
  name: 'lwjgl-freetype',
  groupId: 'lwjgl',
  latestVersion: '3.3.3',
  files: '2',
  description: 'Artifact from lwjgl',
  lastUpdated: '2025-03-13',
  versions: 1,
  license: 'MIT',
  category: 'APIs'
});
artifacts.push({
  name: 'lwjgl-glfw',
  groupId: 'lwjgl',
  latestVersion: '3.3.3',
  files: '2',
  description: 'Artifact from lwjgl',
  lastUpdated: '2025-03-13',
  versions: 1,
  license: 'MIT',
  category: 'APIs'
});
artifacts.push({
  name: 'lwjgl-jemalloc',
  groupId: 'lwjgl',
  latestVersion: '3.3.3',
  files: '2',
  description: 'Artifact from lwjgl',
  lastUpdated: '2025-03-13',
  versions: 1,
  license: 'MIT',
  category: 'APIs'
});
